# Generated by Django 4.0.5 on 2022-07-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.CharField(max_length=100, verbose_name='Name')),
                ('description_test', models.CharField(max_length=255, verbose_name='Description')),
                ('date_test', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='static/questions')),
                ('test_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.test')),
            ],
        ),
    ]
