# Generated by Django 4.0.5 on 2022-07-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='test_num',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='questions.test'),
        ),
    ]
