# Generated by Django 4.0.5 on 2022-07-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questions_test_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=100)),
                ('votes', models.IntegerField()),
                ('question_num', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
            ],
        ),
    ]
